// DIVIDE AND CONQUER PATTERN.
// TAKE A SORTED ARRAY, CONTINUE TO PICK THE MIDDLE OF THE ARRAY.
// TAKE LARGE SET OF DATA AND DIVIDE IT TO SMALLER SECTIONS
// THIS WILL SAVE A LOT OF TIME, HOWEVER IT WILL COMPLICATE CODE.
// USUALLY FOR MORE COMPLEX LISTS AND ARRAYS.
// LOG(N) IS A LOT BETTER THAN O(N)
